// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRQ4f4f48BJMIx1loPyvL2aC59MoXP7i8',
    appId: '1:510630961911:web:bbfcb4bba17dc4791829f2',
    messagingSenderId: '510630961911',
    projectId: 'fir-user-operations-e2566',
    authDomain: 'fir-user-operations-e2566.firebaseapp.com',
    storageBucket: 'fir-user-operations-e2566.appspot.com',
    measurementId: 'G-DXNGH3XET5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgAMxWhKHbuljWktL5iI6dNLCR1IjCEH0',
    appId: '1:510630961911:android:bafe92fcd52bab431829f2',
    messagingSenderId: '510630961911',
    projectId: 'fir-user-operations-e2566',
    storageBucket: 'fir-user-operations-e2566.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNfijVi0wlHLAQoPSbnrtQVlRhWGPPWoc',
    appId: '1:510630961911:ios:2e88a048de6377831829f2',
    messagingSenderId: '510630961911',
    projectId: 'fir-user-operations-e2566',
    storageBucket: 'fir-user-operations-e2566.appspot.com',
    iosClientId: '510630961911-afqtpd9tp1rfm1g2vn4qefc0v7nkq33r.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseUserOperations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNfijVi0wlHLAQoPSbnrtQVlRhWGPPWoc',
    appId: '1:510630961911:ios:2e88a048de6377831829f2',
    messagingSenderId: '510630961911',
    projectId: 'fir-user-operations-e2566',
    storageBucket: 'fir-user-operations-e2566.appspot.com',
    iosClientId: '510630961911-afqtpd9tp1rfm1g2vn4qefc0v7nkq33r.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseUserOperations',
  );
}
